[versions]
agp = "8.12.3"
kotlin = "2.0.21"
coreKtx = "1.17.0"
roomCompiler = "2.8.3"
roomigrantcompiler = "0.3.4"
roomigrantlib = "0.3.4"
roomRuntime = "2.8.3"
roomKtx = "2.8.3"
workMultiprocess = "2.11.0"
workRuntimeKtx = "2.11.0"
navigationUiKtx = "2.9.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
roomigrantcompiler = { module = "com.github.MatrixDev.Roomigrant:RoomigrantCompiler", version.ref = "roomigrantcompiler" }
roomigrantlib = { module = "com.github.MatrixDev.Roomigrant:RoomigrantLib", version.ref = "roomigrantlib" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version = "2.2.0-2.0.2" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationUiKtx" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }

